language: python

sudo: required
dist: trusty

python:
#  - "3.5"
#  - "3.4"
#  - "3.3"
  - "2.7"

#language: c

#compiler:
#  - clang

#https://docs.travis-ci.com/user/trusty-ci-environment/

sudo: required
dist: trusty

#dependencies
#
# what a fucking mess:
#
# https://github.com/travis-ci/travis-ci/issues/4989
# http://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci
#
#
install:
  - sudo apt-get update
  - sudo apt-get install -y wget libprotobuf-dev python-protobuf protobuf-compiler
  - sudo apt-get install -y git llvm-3.5 libclang-3.5-dev clang-3.5
  - sudo apt-get install -y python-pip
  - pip --version
  - pip install setuptools --upgrade
  - pip install wheel
#  - pip install -r requirements.txt
  - export PATH=/usr/lib/llvm-3.5/bin:${PATH}
  - export LLVM_COMPILER=clang
  - export WLLVM_OUTPUT=WARNING
  - export CC=clang
  - export BUILD_HOME=`pwd`
  - export OCCAM_HOME=${BUILD_HOME}/travis_build/occam
  - export OCCAM_LOGFILE=${BUILD_HOME}/travis_build/.occam.log
  - export REPOS=${BUILD_HOME}/travis_build/Repositories

#tests
script:
  - ${BUILD_HOME}/.travis/build.sh
